### ISSUE TITLE
[question] Hosting account is Main account

### ISSUE THREAD

**Issue by srpiatt** [aws-solutions/research-service-workbench-on-aws#459]
In SWB v1, you can have the main account be the hosting account as well, and I tended to use this for sandbox installations. Is this possible in the preview? If yes, how would I configure the hosting account installation to be in the main account? 

I tried it out and the way I have it configured gives me an event bus error.
```
Source EventBus and Target EventBus must not be the same. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: <redacted>; Proxy: null)
```

- Release Version installed 0.1.1

**Comment by nguyen102** [comment]
Currently v2 requires the main account and hosting account be separated. We'll add this request to our backlog.
